database:
  host: localhost
  port: 3306
  user: iplm_user
  password: iplm_password
  database: iplm_db
  charset: utf8mb4
  autocommit: true

schemas:
  processes:
    table_name: processes
    columns:
      id: "INT AUTO_INCREMENT PRIMARY KEY"
      name: "VARCHAR(255) NOT NULL UNIQUE"
      node: "VARCHAR(255) NOT NULL"
      fab: "VARCHAR(100) NOT NULL"
      description: "TEXT"
      created_at: "TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
      updated_at: "TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"

  ips:
    table_name: ips
    columns:
      id: "INT AUTO_INCREMENT PRIMARY KEY"
      name: "VARCHAR(255) NOT NULL UNIQUE"
      type_id: "INT NOT NULL"
      process_id: "INT NOT NULL"
      flavor: "VARCHAR(100)"
      revision: "VARCHAR(50) NOT NULL"
      status: "ENUM('alpha', 'beta', 'production', 'obsolete') NOT NULL"
      provider: "VARCHAR(255) NOT NULL"
      ip_components: "JSON"
      description: "TEXT"
      documentation: "TEXT"
      created_at: "TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
      updated_at: "TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"
    foreign_keys:
      type_id: "FOREIGN KEY (type_id) REFERENCES types(id) ON DELETE CASCADE"
      process_id: "FOREIGN KEY (process_id) REFERENCES processes(id) ON DELETE CASCADE"

  types:
    table_name: types
    columns:
      id: "INT AUTO_INCREMENT PRIMARY KEY"
      name: "VARCHAR(255) NOT NULL"
      parent_id: "INT NULL"
      path: "VARCHAR(500) NOT NULL"
      level: "INT NOT NULL DEFAULT 0"
      description: "TEXT"
      created_at: "TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
      updated_at: "TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"
    foreign_keys:
      parent_id: "FOREIGN KEY (parent_id) REFERENCES types(id) ON DELETE CASCADE"
    indexes:
      path: "INDEX idx_path (path(191))"
      parent_id: "INDEX idx_parent_id (parent_id)"

